import type { Metadata } from "next";
import MarketingNav from "@/components/marketing/MarketingNav";
import MarketingFooter from "@/components/marketing/MarketingFooter";

export const metadata: Metadata = {
  title: "Privacy Policy — Otter Hire",
  description: "How Otter Hire collects, uses, and protects your personal data.",
};

const sections = [
  {
    title: "Introduction",
    content: `Welcome to Otter Hire ("us", "we", or "our"). Otter Hire operates otter.bz (hereinafter referred to as "Service").

Our Privacy Policy governs your visit to otter.bz and explains how we collect, safeguard, and disclose information that results from your use of our Service.

We use your data to provide and improve our Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used herein have the same meanings as in our Terms and Conditions.

Our Terms and Conditions ("Terms") govern all use of our Service and together with this Privacy Policy constitute your agreement with us.`,
  },
  {
    title: "Definitions",
    content: `Service means the otter.bz website operated by Otter Hire.

Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).

Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).

Cookies are small files stored on your device (computer or mobile device).

Data Controller means a natural or legal person who determines the purposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.

Data Processors (or Service Providers) means any natural or legal person who processes the data on behalf of the Data Controller.

The User is the individual using our Service, corresponding to the Data Subject who is the subject of Personal Data.`,
  },
  {
    title: "Information Collection and Use",
    content: `We collect several different types of information for various purposes to provide and improve our Service to you.

You are responsible for complying with the laws of the jurisdiction from which you are accessing this site. Any information submitted by you through this site shall be deemed non-confidential and non-proprietary unless expressly stated otherwise. You represent that you have the lawful right to submit such information.`,
  },
  {
    title: "Types of Data Collected",
    subsections: [
      {
        subtitle: "Personal Data",
        content: `While using our Service, we may ask you to provide certain personally identifiable information that can be used to contact or identify you ("Personal Data"). This may include, but is not limited to:

• Email address
• First name and last name
• Phone number
• Address, Country, State, Province, ZIP/Postal code, City
• Cookies and Usage Data

We may use your Personal Data to contact you with product updates or other information relevant to the Service. You may opt out of receiving any or all of these communications by following the unsubscribe link.`,
      },
      {
        subtitle: "Usage Data",
        content: `We may also collect information that your browser sends whenever you visit our Service or when you access the Service through any device ("Usage Data"). This may include your computer's Internet Protocol address (IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.`,
      },
      {
        subtitle: "Tracking & Cookies Data",
        content: `We use cookies and similar tracking technologies to track activity on our Service. Cookies are files with a small amount of data which may include an anonymous unique identifier. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.

Types of cookies we use:
• Session Cookies: to operate our Service
• Preference Cookies: to remember your preferences and settings
• Security Cookies: for security purposes`,
      },
    ],
  },
  {
    title: "Use of Data",
    content: `Otter Hire uses the collected data for the following purposes:

• To provide and maintain our Service
• To notify you about changes to our Service
• To allow you to participate in interactive features of our Service
• To provide customer support
• To gather analysis so that we can improve our Service
• To monitor the usage of our Service
• To detect, prevent, and address technical issues
• To carry out our obligations arising from any contracts entered into between you and us
• To provide you with notices about your account
• For any other purpose with your consent`,
  },
  {
    title: "Retention of Data",
    content: `We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.

Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or improve the functionality of our Service, or we are legally obligated to retain this data for longer periods.`,
  },
  {
    title: "Transfer of Data",
    content: `Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.

Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer. Otter Hire will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organisation or country unless there are adequate controls in place.`,
  },
  {
    title: "Disclosure of Data",
    content: `We may disclose personal information that we collect or that you provide in the following circumstances:

• Disclosure for Law Enforcement: Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.

• Business Transaction: If Otter Hire is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred.

• Other cases: To contractors, service providers, and other third parties we use to support our business; to fulfil the purpose for which you provide it; with your consent in any other cases; or if we believe disclosure is necessary to protect the rights, property, or safety of Otter Hire, our users, or others.`,
  },
  {
    title: "Security of Data",
    content: `The security of your data is important to us. However, remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.`,
  },
  {
    title: "Your Data Protection Rights under GDPR",
    content: `If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights covered by GDPR. We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.

If you wish to be informed about what Personal Data we hold about you or want it removed from our systems, please email us at support@otter.bz.

Your rights include:
• The right to access, update, or delete the information we have on you
• The right of rectification — to have inaccurate information corrected
• The right to object to our processing of your Personal Data
• The right of restriction on processing
• The right to data portability
• The right to withdraw consent at any time

You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data.`,
  },
  {
    title: "Your Rights under CalOPPA",
    content: `According to CalOPPA we agree to the following:

• Users can visit our site anonymously
• Our Privacy Policy link includes the word "Privacy" and can easily be found on the homepage
• Users will be notified of any privacy policy changes on this Privacy Policy page
• Users are able to change their personal information by emailing us at support@otter.bz

Our Policy on "Do Not Track" Signals: We honor Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place.`,
  },
  {
    title: "Your Rights under CCPA",
    content: `If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data, and request that we do not sell it.

You may ask us:
• What personal information we have about you (categories, sources, business purpose, third parties, specific pieces collected)
• To delete your personal information from our records
• To stop selling your personal information — we do not sell or rent your personal information to any third parties for any purpose

To exercise your California data protection rights, please contact us at support@otter.bz.`,
  },
  {
    title: "Service Providers",
    content: `We may employ third-party companies and individuals to facilitate our Service ("Service Providers"), provide the Service on our behalf, perform Service-related services, or assist us in analysing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.`,
  },
  {
    title: "Links to Other Sites",
    content: `Our Service may contain links to other sites that are not operated by us. If you click a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.`,
  },
  {
    title: "Children's Privacy",
    content: `Our Service is not intended for use by children under the age of 18. We do not knowingly collect personally identifiable information from children under 18. If you become aware that a child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.`,
  },
  {
    title: "Changes to This Privacy Policy",
    content: `We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the effective date. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.`,
  },
  {
    title: "Contact Us",
    content: `If you have any questions about this Privacy Policy, please contact us at support@otter.bz.`,
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="marketing-root min-h-screen bg-white text-foreground">
      <MarketingNav onLegalPage />

      {/* Hero */}
      <div className="border-b border-black/6 bg-[#f7f8fc] px-4 pt-32 pb-14 text-center sm:pt-36 sm:pb-20">
        <p className="text-[11px] font-semibold uppercase tracking-[0.22em] text-slate-400">
          Legal
        </p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight text-slate-900 sm:text-5xl">
          Privacy Policy
        </h1>
      </div>

      {/* Content */}
      <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20">
        <div className="mb-12 rounded-2xl border border-black/8 bg-slate-50 p-6 text-sm leading-7 text-slate-600">
          You are responsible for complying with the laws of the jurisdiction from which you are
          accessing this site. The User&apos;s right to privacy is of paramount importance to Otter
          Hire. Any information provided by the User will not be shared with any third party unless
          identified as such elsewhere.
        </div>

        <div className="space-y-12">
          {sections.map((section, i) => (
            <section key={i}>
              <h2 className="text-xl font-semibold text-slate-900">
                {i + 1}. {section.title}
              </h2>
              {"subsections" in section && section.subsections ? (
                <div className="mt-4 space-y-6">
                  {section.subsections.map((sub, j) => (
                    <div key={j}>
                      <h3 className="text-base font-semibold text-slate-700">{sub.subtitle}</h3>
                      <p className="mt-2 whitespace-pre-line text-base leading-7 text-slate-600">
                        {sub.content}
                      </p>
                    </div>
                  ))}
                </div>
              ) : (
                <p className="mt-4 whitespace-pre-line text-base leading-7 text-slate-600">
                  {"content" in section ? section.content : ""}
                </p>
              )}
            </section>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="bg-[linear-gradient(180deg,#ffffff_0%,#fbfbfd_100%)] px-4 pb-6 sm:px-6">
        <MarketingFooter />
      </div>
    </div>
  );
}
